In [72]:
import pandas as pd
import multiprocessing

# Crie um arquivo Jupyter Notebook e realize as seguintes operações:

## a) Ler o dataset fakeTelegram.BR_2022.csv, o qual está disponível no link a seguir: https://drive.google.com/file/d/1c_hLzk85pYw-huHSnFYZM_gn-dUsYRDm/view?usp=drive_link

In [114]:
# Abre do aquivo CSV e printa alguns elementos
df = pd.read_csv("./fakeTelegram.BR_2022.csv")
df

,date_message,id_member_anonymous,id_group_anonymous,media,media_type,media_url,has_media,has_media_url,trava_zap,text_content_anonymous,dataset_info_id,date_system,score_sentiment,score_misinformation,id_message,message_type,messenger,media_name,media_md5
0,2022-10-05 06:25:04,1078cc958f0febe28f4d03207660715f,12283e08a2eb5789201e105b34489ee7,NaN,NaN,NaN,False,False,False,Então é Fato Renato o áudio que eu ouvi no wha...,5,2022-10-05 06:25:28.863641,0.0000,NaN,16385,Texto,telegram,NaN,NaN
1,2022-10-05 06:25:08,NaN,12283e08a2eb5789201e105b34489ee7,NaN,NaN,NaN,False,False,False,"Saiu no YouTube do presidente a 8 horas atrás,...",5,2022-10-05 06:25:28.926311,0.0644,NaN,16386,Texto,telegram,NaN,NaN
2,2022-10-05 06:26:28,92a2d8fd7144074f659d1d29dc3751da,9f2d7394334eb224c061c9740b5748fc,NaN,NaN,NaN,False,False,False,"É isso, nossa parte já foi quase toda feita. N...",5,2022-10-05 06:26:29.361949,-0.3551,0.157242,16366,Texto,telegram,NaN,NaN
3,2022-10-05 06:27:28,d60aa38f62b4977426b70944af4aff72,c8f2de56550ed0bf85249608b7ead93d,94dca4cda503100ebfda7ce2bcc060eb.jpg,image/jpg,NaN,True,False,False,GENTE ACHEI ELES EM UMA SEITA MAÇONÁRICA,5,2022-10-05 06:27:29.935624,0.0000,NaN,19281,Imagem,telegram,NaN,94dca4cda503100ebfda7ce2bcc060eb
4,2022-10-05 06:27:44,cd6979b0b5265f08468fa1689b6300ce,e56ec342fc599ebb4ed89655eb6f03aa,5ad5c8bbe9da93a37fecf3e5aa5b0637.jpg,image/jpg,NaN,True,False,False,NaN,5,2022-10-05 06:28:29.316325,NaN,NaN,507185,Imagem,telegram,NaN,5ad5c8bbe9da93a37fecf3e5aa5b0637
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
557581,2022-11-11 12:06:15,333e9869f23dbd4682d1be382d9c1e59,e56ec342fc599ebb4ed89655eb6f03aa,25e43b6a58b848c43ad5b5f9e979822a.jpg,url,https://terrabrasilnoticias.com/2022/11/bndes-...,True,True,False,"BNDES tem lucro de R$ 9,6 bilhões no terceiro ...",5,2022-11-16 14:49:39.146502,0.1027,NaN,575796,Url,telegram,NaN,25e43b6a58b848c43ad5b5f9e979822a
557582,2022-11-11 12:09:08,NaN,5b10d7739171149be6d9961e3350c071,657949d03e4088f6b332e2686ccd3221.jpg,url,https://youtu.be/8g1Vz9_0xVk,True,True,False,https://youtu.be/8g1Vz9_0xVk,5,2022-11-16 14:49:39.847434,0.0000,NaN,1286443,Url,telegram,NaN,657949d03e4088f6b332e2686ccd3221
557583,2022-11-11 12:09:47,NaN,1590a03f43b5ba4b6147a1c5e1dd357b,a21848a61045380a6483866daed0ca0e.jpg,image/jpg,https://t.me/vemprasruas,True,True,False,"Empresários, demitam os petistas primeiro.\n\n...",5,2022-11-16 14:49:39.922279,0.0000,NaN,13294,Imagem,telegram,NaN,a21848a61045380a6483866daed0ca0e
557584,2022-11-11 12:09:46,NaN,5b10d7739171149be6d9961e3350c071,a21848a61045380a6483866daed0ca0e.jpg,image/jpg,https://t.me/vemprasruas,True,True,False,"Empresários, demitam os petistas primeiro.\n\n...",5,2022-11-16 14:49:39.992932,0.0000,NaN,1286444,Imagem,telegram,NaN,a21848a61045380a6483866daed0ca0e
557585,2022-11-11 12:09:48,NaN,b11f2df64ac19aad47a50accf32052d6,a21848a61045380a6483866daed0ca0e.jpg,image/jpg,https://t.me/vemprasruas,True,True,False,"Empresários, demitam os petistas primeiro.\n\n...",5,2022-11-16 14:49:40.064006,0.0000,NaN,192127,Imagem,telegram,NaN,a21848a61045380a6483866daed0ca0e

In [115]:
# Printa as colunas existente no dataset
df.columns

Index(['date_message', 'id_member_anonymous', 'id_group_anonymous', 'media',
       'media_type', 'media_url', 'has_media', 'has_media_url', 'trava_zap',
       'text_content_anonymous', 'dataset_info_id', 'date_system',
       'score_sentiment', 'score_misinformation', 'id_message', 'message_type',
       'messenger', 'media_name', 'media_md5'],
      dtype='object')

In [ ]:
# Printa as estastísticas das colunas numéricas do dataset
df.describe()

       dataset_info_id  score_sentiment  score_misinformation    id_message
count         557586.0    444157.000000         167238.000000  5.575860e+05
mean               5.0         0.017330              0.312245  4.450617e+05
std                0.0         0.464165              0.293699  4.860211e+05
min                5.0        -1.000000              0.000003  2.000000e+00
25%                5.0        -0.177900              0.078454  2.127500e+04
50%                5.0         0.000000              0.197577  1.210935e+05
75%                5.0         0.318200              0.490351  9.726045e+05
max                5.0         0.999200              1.000000  1.516436e+06

## b)  Identificar e listar as posições (células) contendo valores faltantes.

In [74]:
# Identifica os valores nulos
df.isnull()

,date_message,id_member_anonymous,id_group_anonymous,media,media_type,media_url,has_media,has_media_url,trava_zap,text_content_anonymous,dataset_info_id,date_system,score_sentiment,score_misinformation,id_message,message_type,messenger,media_name,media_md5
0,False,False,False,True,True,True,False,False,False,False,False,False,False,True,False,False,False,True,True
1,False,True,False,True,True,True,False,False,False,False,False,False,False,True,False,False,False,True,True
2,False,False,False,True,True,True,False,False,False,False,False,False,False,False,False,False,False,True,True
3,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False,True,False
4,False,False,False,False,False,True,False,False,False,True,False,False,True,True,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
557581,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True,False
557582,False,True,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True,False
557583,False,True,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True,False
557584,False,True,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True,False
557585,False,True,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True,False

In [75]:
# Cria um dicionário com os valores nulos armazenando os índices e colunas
array_faltantes = []

# Primeiro loop percorre as colunas 
for coluns in df.columns:
    # Segundo loop percorre as linhas da coluna
    for i in range(len(df)):
        # Verifica se o valor é nulo
        if pd.isna(df.at[i, coluns]):
            # Se for nulo, adiciona o índice e a coluna ao array de dicionários
            array_faltantes.append((i, coluns))

In [76]:
# Printa os valores nulos em cada coluna
array_faltantes

[(1, 'id_member_anonymous'),
 (5, 'id_member_anonymous'),
 (11, 'id_member_anonymous'),
 (12, 'id_member_anonymous'),
 (14, 'id_member_anonymous'),
 (17, 'id_member_anonymous'),
 (21, 'id_member_anonymous'),
 (22, 'id_member_anonymous'),
 (24, 'id_member_anonymous'),
 (25, 'id_member_anonymous'),
 (26, 'id_member_anonymous'),
 (27, 'id_member_anonymous'),
 (29, 'id_member_anonymous'),
 (30, 'id_member_anonymous'),
 (31, 'id_member_anonymous'),
 (32, 'id_member_anonymous'),
 (33, 'id_member_anonymous'),
 (34, 'id_member_anonymous'),
 (35, 'id_member_anonymous'),
 (36, 'id_member_anonymous'),
 (37, 'id_member_anonymous'),
 (38, 'id_member_anonymous'),
 (42, 'id_member_anonymous'),
 (45, 'id_member_anonymous'),
 (51, 'id_member_anonymous'),
 (52, 'id_member_anonymous'),
 (54, 'id_member_anonymous'),
 (56, 'id_member_anonymous'),
 (57, 'id_member_anonymous'),
 (59, 'id_member_anonymous'),
 (64, 'id_member_anonymous'),
 (65, 'id_member_anonymous'),
 (68, 'id_member_anonymous'),
 (69, 'id_member_anonymous'),
 (70, 'id_member_anonymous'),
 (73, 'id_member_anonymous'),
 (74, 'id_member_anonymous'),
 (75, 'id_member_anonymous'),
 (78, 'id_member_anonymous'),
 (79, 'id_member_anonymous'),
 (80, 'id_member_anonymous'),
 (81, 'id_member_anonymous'),
 (82, 'id_member_anonymous'),
 (84, 'id_member_anonymous'),
 (89, 'id_member_anonymous'),
 (90, 'id_member_anonymous'),
 (95, 'id_member_anonymous'),
 (99, 'id_member_anonymous'),
 (100, 'id_member_anonymous'),
 (103, 'id_member_anonymous'),
 (108, 'id_member_anonymous'),
 (111, 'id_member_anonymous'),
 (112, 'id_member_anonymous'),
 (113, 'id_member_anonymous'),
 (114, 'id_member_anonymous'),
 (118, 'id_member_anonymous'),
 (119, 'id_member_anonymous'),
 (120, 'id_member_anonymous'),
 (121, 'id_member_anonymous'),
 (124, 'id_member_anonymous'),
 (126, 'id_member_anonymous'),
 (127, 'id_member_anonymous'),
 (128, 'id_member_anonymous'),
 (130, 'id_member_anonymous'),
 (131, 'id_member_anonymous'),
 (132, 'id_member_anonymous'),
 (133, 'id_member_anonymous'),
 (146, 'id_member_anonymous'),
 (147, 'id_member_anonymous'),
 (149, 'id_member_anonymous'),
 (153, 'id_member_anonymous'),
 (155, 'id_member_anonymous'),
 (156, 'id_member_anonymous'),
 (158, 'id_member_anonymous'),
 (159, 'id_member_anonymous'),
 (160, 'id_member_anonymous'),
 (163, 'id_member_anonymous'),
 (164, 'id_member_anonymous'),
 (165, 'id_member_anonymous'),
 (166, 'id_member_anonymous'),
 (167, 'id_member_anonymous'),
 (168, 'id_member_anonymous'),
 (169, 'id_member_anonymous'),
 (170, 'id_member_anonymous'),
 (171, 'id_member_anonymous'),
 (173, 'id_member_anonymous'),
 (174, 'id_member_anonymous'),
 (175, 'id_member_anonymous'),
 (176, 'id_member_anonymous'),
 (178, 'id_member_anonymous'),
 (179, 'id_member_anonymous'),
 (180, 'id_member_anonymous'),
 (182, 'id_member_anonymous'),
 (184, 'id_member_anonymous'),
 (185, 'id_member_anonymous'),
 (186, 'id_member_anonymous'),
 (187, 'id_member_anonymous'),
 (188, 'id_member_anonymous'),
 (189, 'id_member_anonymous'),
 (191, 'id_member_anonymous'),
 (192, 'id_member_anonymous'),
 (193, 'id_member_anonymous'),
 (194, 'id_member_anonymous'),
 (195, 'id_member_anonymous'),
 (196, 'id_member_anonymous'),
 (197, 'id_member_anonymous'),
 (198, 'id_member_anonymous'),
 (199, 'id_member_anonymous'),
 (200, 'id_member_anonymous'),
 (201, 'id_member_anonymous'),
 (202, 'id_member_anonymous'),
 (203, 'id_member_anonymous'),
 (204, 'id_member_anonymous'),
 (205, 'id_member_anonymous'),
 (206, 'id_member_anonymous'),
 (207, 'id_member_anonymous'),
 (208, 'id_member_anonymous'),
 (209, 'id_member_anonymous'),
 (211, 'id_member_anonymous'),
 (212, 'id_member_anonymous'),
 (214, 'id_member_anonymous'),
 (215, 'id_member_anonymous'),
 (217, 'id_member_anonymous'),
 (223, 'id_member_anonymous'),
 (231, 'id_member_anonymous'),
 (233, 'id_member_anonymous'),
 (234, 'id_member_anonymous'),
 (236, 'id_member_anonymous'),
 (237, 'id_member_anonymous'),
 (238, 'id_member_anonymous'),
 (239, 'id_member_anonymous'),
 (240, 'id_member_anonymous'),
 (241, 'id_member_anonymous'),
 (242, 'id_member_anonymous'),
 (243, 'id_member_anonymous'),
 (244, 'id_member_anonymous'),
 (246, 'id_member_anonymous'),
 (247, 'id_member_anonymous'),
 (248, 'id_member_anonymous'),
 (250, 'id_member_anonymous'),
 (252, 'id_member_anonymous'),
 (253, 'id_member_anonymous'),
 (254, 'id_member_anonymous'),
 (255, 'id_member_anonymous'),
 (256, 'id_member_anonymous'),
 (257, 'id_member_anonymous'),
 (258, 'id_member_anonymous'),
 (259, 'id_member_anonymous'),
 (260, 'id_member_anonymous'),
 (261, 'id_member_anonymous'),
 (262, 'id_member_anonymous'),
 (266, 'id_member_anonymous'),
 (267, 'id_member_anonymous'),
 (268, 'id_member_anonymous'),
 (269, 'id_member_anonymous'),
 (273, 'id_member_anonymous'),
 (274, 'id_member_anonymous'),
 (275, 'id_member_anonymous'),
 (276, 'id_member_anonymous'),
 (277, 'id_member_anonymous'),
 (278, 'id_member_anonymous'),
 (281, 'id_member_anonymous'),
 (285, 'id_member_anonymous'),
 (287, 'id_member_anonymous'),
 (288, 'id_member_anonymous'),
 (289, 'id_member_anonymous'),
 (290, 'id_member_anonymous'),
 (291, 'id_member_anonymous'),
 (292, 'id_member_anonymous'),
 (293, 'id_member_anonymous'),
 (296, 'id_member_anonymous'),
 (297, 'id_member_anonymous'),
 (298, 'id_member_anonymous'),
 (301, 'id_member_anonymous'),
 (302, 'id_member_anonymous'),
 (303, 'id_member_anonymous'),
 (304, 'id_member_anonymous'),
 (307, 'id_member_anonymous'),
 (308, 'id_member_anonymous'),
 (309, 'id_member_anonymous'),
 (310, 'id_member_anonymous'),
 (311, 'id_member_anonymous'),
 (312, 'id_member_anonymous'),
 (313, 'id_member_anonymous'),
 (318, 'id_member_anonymous'),
 (321, 'id_member_anonymous'),
 (322, 'id_member_anonymous'),
 (324, 'id_member_anonymous'),
 (325, 'id_member_anonymous'),
 (326, 'id_member_anonymous'),
 (330, 'id_member_anonymous'),
 (332, 'id_member_anonymous'),
 (333, 'id_member_anonymous'),
 (334, 'id_member_anonymous'),
 (335, 'id_member_anonymous'),
 (336, 'id_member_anonymous'),
 (337, 'id_member_anonymous'),
 (338, 'id_member_anonymous'),
 (339, 'id_member_anonymous'),
 (340, 'id_member_anonymous'),
 (341, 'id_member_anonymous'),
 (342, 'id_member_anonymous'),
 (347, 'id_member_anonymous'),
 (348, 'id_member_anonymous'),
 (349, 'id_member_anonymous'),
 (350, 'id_member_anonymous'),
 (352, 'id_member_anonymous'),
 (355, 'id_member_anonymous'),
 (359, 'id_member_anonymous'),
 (361, 'id_member_anonymous'),
 (362, 'id_member_anonymous'),
 (363, 'id_member_anonymous'),
 (365, 'id_member_anonymous'),
 (367, 'id_member_anonymous'),
 (368, 'id_member_anonymous'),
 (374, 'id_member_anonymous'),
 (379, 'id_member_anonymous'),
 (383, 'id_member_anonymous'),
 (384, 'id_member_anonymous'),
 (385, 'id_member_anonymous'),
 (387, 'id_member_anonymous'),
 (389, 'id_member_anonymous'),
 (391, 'id_member_anonymous'),
 (392, 'id_member_anonymous'),
 (393, 'id_member_anonymous'),
 (394, 'id_member_anonymous'),
 (398, 'id_member_anonymous'),
 (399, 'id_member_anonymous'),
 (400, 'id_member_anonymous'),
 (402, 'id_member_anonymous'),
 (403, 'id_member_anonymous'),
 (404, 'id_member_anonymous'),
 (405, 'id_member_anonymous'),
 (407, 'id_member_anonymous'),
 (409, 'id_member_anonymous'),
 (410, 'id_member_anonymous'),
 (415, 'id_member_anonymous'),
 (416, 'id_member_anonymous'),
 (419, 'id_member_anonymous'),
 (420, 'id_member_anonymous'),
 (421, 'id_member_anonymous'),
 (422, 'id_member_anonymous'),
 (423, 'id_member_anonymous'),
 (425, 'id_member_anonymous'),
 (426, 'id_member_anonymous'),
 (427, 'id_member_anonymous'),
 (428, 'id_member_anonymous'),
 (429, 'id_member_anonymous'),
 (430, 'id_member_anonymous'),
 (431, 'id_member_anonymous'),
 (432, 'id_member_anonymous'),
 (433, 'id_member_anonymous'),
 (435, 'id_member_anonymous'),
 (437, 'id_member_anonymous'),
 (438, 'id_member_anonymous'),
 (441, 'id_member_anonymous'),
 (442, 'id_member_anonymous'),
 (446, 'id_member_anonymous'),
 (447, 'id_member_anonymous'),
 (448, 'id_member_anonymous'),
 (451, 'id_member_anonymous'),
 (452, 'id_member_anonymous'),
 (453, 'id_member_anonymous'),
 (456, 'id_member_anonymous'),
 (460, 'id_member_anonymous'),
 (462, 'id_member_anonymous'),
 (463, 'id_member_anonymous'),
 (468, 'id_member_anonymous'),
 (472, 'id_member_anonymous'),
 (473, 'id_member_anonymous'),
 (474, 'id_member_anonymous'),
 (476, 'id_member_anonymous'),
 (477, 'id_member_anonymous'),
 (478, 'id_member_anonymous'),
 (479, 'id_member_anonymous'),
 (480, 'id_member_anonymous'),
 (481, 'id_member_anonymous'),
 (482, 'id_member_anonymous'),
 (486, 'id_member_anonymous'),
 (487, 'id_member_anonymous'),
 (488, 'id_member_anonymous'),
 (490, 'id_member_anonymous'),
 (491, 'id_member_anonymous'),
 (492, 'id_member_anonymous'),
 (493, 'id_member_anonymous'),
 (495, 'id_member_anonymous'),
 (497, 'id_member_anonymous'),
 (500, 'id_member_anonymous'),
 (501, 'id_member_anonymous'),
 (503, 'id_member_anonymous'),
 (506, 'id_member_anonymous'),
 (509, 'id_member_anonymous'),
 (510, 'id_member_anonymous'),
 (512, 'id_member_anonymous'),
 (513, 'id_member_anonymous'),
 (514, 'id_member_anonymous'),
 (516, 'id_member_anonymous'),
 (518, 'id_member_anonymous'),
 (519, 'id_member_anonymous'),
 (520, 'id_member_anonymous'),
 (521, 'id_member_anonymous'),
 (523, 'id_member_anonymous'),
 (524, 'id_member_anonymous'),
 (527, 'id_member_anonymous'),
 (528, 'id_member_anonymous'),
 (530, 'id_member_anonymous'),
 (538, 'id_member_anonymous'),
 (539, 'id_member_anonymous'),
 (540, 'id_member_anonymous'),
 (541, 'id_member_anonymous'),
 (543, 'id_member_anonymous'),
 (544, 'id_member_anonymous'),
 (546, 'id_member_anonymous'),
 (547, 'id_member_anonymous'),
 (549, 'id_member_anonymous'),
 (552, 'id_member_anonymous'),
 (553, 'id_member_anonymous'),
 (554, 'id_member_anonymous'),
 (556, 'id_member_anonymous'),
 (558, 'id_member_anonymous'),
 (559, 'id_member_anonymous'),
 (561, 'id_member_anonymous'),
 (564, 'id_member_anonymous'),
 (567, 'id_member_anonymous'),
 (577, 'id_member_anonymous'),
 (578, 'id_member_anonymous'),
 (580, 'id_member_anonymous'),
 (581, 'id_member_anonymous'),
 (587, 'id_member_anonymous'),
 (588, 'id_member_anonymous'),
 (589, 'id_member_anonymous'),
 (590, 'id_member_anonymous'),
 (591, 'id_member_anonymous'),
 (593, 'id_member_anonymous'),
 (595, 'id_member_anonymous'),
 (596, 'id_member_anonymous'),
 (598, 'id_member_anonymous'),
 (599, 'id_member_anonymous'),
 (601, 'id_member_anonymous'),
 (602, 'id_member_anonymous'),
 (603, 'id_member_anonymous'),
 (604, 'id_member_anonymous'),
 (606, 'id_member_anonymous'),
 (607, 'id_member_anonymous'),
 (608, 'id_member_anonymous'),
 (609, 'id_member_anonymous'),
 (610, 'id_member_anonymous'),
 (611, 'id_member_anonymous'),
 (612, 'id_member_anonymous'),
 (613, 'id_member_anonymous'),
 (614, 'id_member_anonymous'),
 (616, 'id_member_anonymous'),
 (617, 'id_member_anonymous'),
 (618, 'id_member_anonymous'),
 (619, 'id_member_anonymous'),
 (621, 'id_member_anonymous'),
 (622, 'id_member_anonymous'),
 (624, 'id_member_anonymous'),
 (626, 'id_member_anonymous'),
 (627, 'id_member_anonymous'),
 (629, 'id_member_anonymous'),
 (632, 'id_member_anonymous'),
 (635, 'id_member_anonymous'),
 (637, 'id_member_anonymous'),
 (638, 'id_member_anonymous'),
 (641, 'id_member_anonymous'),
 (642, 'id_member_anonymous'),
 (645, 'id_member_anonymous'),
 (650, 'id_member_anonymous'),
 (651, 'id_member_anonymous'),
 (652, 'id_member_anonymous'),
 (653, 'id_member_anonymous'),
 (654, 'id_member_anonymous'),
 (655, 'id_member_anonymous'),
 (656, 'id_member_anonymous'),
 (657, 'id_member_anonymous'),
 (658, 'id_member_anonymous'),
 (659, 'id_member_anonymous'),
 (660, 'id_member_anonymous'),
 (662, 'id_member_anonymous'),
 (664, 'id_member_anonymous'),
 (665, 'id_member_anonymous'),
 (666, 'id_member_anonymous'),
 (667, 'id_member_anonymous'),
 (668, 'id_member_anonymous'),
 (669, 'id_member_anonymous'),
 (670, 'id_member_anonymous'),
 (675, 'id_member_anonymous'),
 (676, 'id_member_anonymous'),
 (677, 'id_member_anonymous'),
 (678, 'id_member_anonymous'),
 (679, 'id_member_anonymous'),
 (680, 'id_member_anonymous'),
 (682, 'id_member_anonymous'),
 (683, 'id_member_anonymous'),
 (684, 'id_member_anonymous'),
 (685, 'id_member_anonymous'),
 (686, 'id_member_anonymous'),
 (687, 'id_member_anonymous'),
 (688, 'id_member_anonymous'),
 (690, 'id_member_anonymous'),
 (691, 'id_member_anonymous'),
 (692, 'id_member_anonymous'),
 (693, 'id_member_anonymous'),
 (696, 'id_member_anonymous'),
 (697, 'id_member_anonymous'),
 (698, 'id_member_anonymous'),
 (699, 'id_member_anonymous'),
 (700, 'id_member_anonymous'),
 (701, 'id_member_anonymous'),
 (702, 'id_member_anonymous'),
 (705, 'id_member_anonymous'),
 (706, 'id_member_anonymous'),
 (707, 'id_member_anonymous'),
 (710, 'id_member_anonymous'),
 (713, 'id_member_anonymous'),
 (714, 'id_member_anonymous'),
 (715, 'id_member_anonymous'),
 (717, 'id_member_anonymous'),
 (720, 'id_member_anonymous'),
 (721, 'id_member_anonymous'),
 (722, 'id_member_anonymous'),
 (724, 'id_member_anonymous'),
 (726, 'id_member_anonymous'),
 (727, 'id_member_anonymous'),
 (728, 'id_member_anonymous'),
 (729, 'id_member_anonymous'),
 (730, 'id_member_anonymous'),
 (731, 'id_member_anonymous'),
 (732, 'id_member_anonymous'),
 (733, 'id_member_anonymous'),
 (734, 'id_member_anonymous'),
 (735, 'id_member_anonymous'),
 (738, 'id_member_anonymous'),
 (741, 'id_member_anonymous'),
 (742, 'id_member_anonymous'),
 (744, 'id_member_anonymous'),
 (745, 'id_member_anonymous'),
 (748, 'id_member_anonymous'),
 (751, 'id_member_anonymous'),
 (753, 'id_member_anonymous'),
 (754, 'id_member_anonymous'),
 (755, 'id_member_anonymous'),
 (757, 'id_member_anonymous'),
 (758, 'id_member_anonymous'),
 (759, 'id_member_anonymous'),
 (761, 'id_member_anonymous'),
 (762, 'id_member_anonymous'),
 (763, 'id_member_anonymous'),
 (764, 'id_member_anonymous'),
 (766, 'id_member_anonymous'),
 (768, 'id_member_anonymous'),
 (770, 'id_member_anonymous'),
 (772, 'id_member_anonymous'),
 (774, 'id_member_anonymous'),
 (775, 'id_member_anonymous'),
 (777, 'id_member_anonymous'),
 (778, 'id_member_anonymous'),
 (780, 'id_member_anonymous'),
 (781, 'id_member_anonymous'),
 (782, 'id_member_anonymous'),
 (784, 'id_member_anonymous'),
 (785, 'id_member_anonymous'),
 (786, 'id_member_anonymous'),
 (787, 'id_member_anonymous'),
 (790, 'id_member_anonymous'),
 (791, 'id_member_anonymous'),
 (792, 'id_member_anonymous'),
 (794, 'id_member_anonymous'),
 (795, 'id_member_anonymous'),
 (797, 'id_member_anonymous'),
 (798, 'id_member_anonymous'),
 (801, 'id_member_anonymous'),
 (803, 'id_member_anonymous'),
 (805, 'id_member_anonymous'),
 (806, 'id_member_anonymous'),
 (811, 'id_member_anonymous'),
 (813, 'id_member_anonymous'),
 (814, 'id_member_anonymous'),
 (815, 'id_member_anonymous'),
 (816, 'id_member_anonymous'),
 (819, 'id_member_anonymous'),
 (820, 'id_member_anonymous'),
 (821, 'id_member_anonymous'),
 (823, 'id_member_anonymous'),
 (824, 'id_member_anonymous'),
 (825, 'id_member_anonymous'),
 (826, 'id_member_anonymous'),
 (827, 'id_member_anonymous'),
 (828, 'id_member_anonymous'),
 (829, 'id_member_anonymous'),
 (830, 'id_member_anonymous'),
 (831, 'id_member_anonymous'),
 (832, 'id_member_anonymous'),
 (834, 'id_member_anonymous'),
 (836, 'id_member_anonymous'),
 (837, 'id_member_anonymous'),
 (839, 'id_member_anonymous'),
 (840, 'id_member_anonymous'),
 (841, 'id_member_anonymous'),
 (842, 'id_member_anonymous'),
 (843, 'id_member_anonymous'),
 (844, 'id_member_anonymous'),
 (845, 'id_member_anonymous'),
 (846, 'id_member_anonymous'),
 (847, 'id_member_anonymous'),
 (851, 'id_member_anonymous'),
 (852, 'id_member_anonymous'),
 (853, 'id_member_anonymous'),
 (854, 'id_member_anonymous'),
 (855, 'id_member_anonymous'),
 (856, 'id_member_anonymous'),
 (857, 'id_member_anonymous'),
 (858, 'id_member_anonymous'),
 (859, 'id_member_anonymous'),
 (861, 'id_member_anonymous'),
 (862, 'id_member_anonymous'),
 (864, 'id_member_anonymous'),
 (865, 'id_member_anonymous'),
 (866, 'id_member_anonymous'),
 (867, 'id_member_anonymous'),
 (868, 'id_member_anonymous'),
 (870, 'id_member_anonymous'),
 (871, 'id_member_anonymous'),
 (872, 'id_member_anonymous'),
 (876, 'id_member_anonymous'),
 (877, 'id_member_anonymous'),
 (878, 'id_member_anonymous'),
 (879, 'id_member_anonymous'),
 (883, 'id_member_anonymous'),
 (885, 'id_member_anonymous'),
 (887, 'id_member_anonymous'),
 (888, 'id_member_anonymous'),
 (890, 'id_member_anonymous'),
 (891, 'id_member_anonymous'),
 (892, 'id_member_anonymous'),
 (893, 'id_member_anonymous'),
 (894, 'id_member_anonymous'),
 (895, 'id_member_anonymous'),
 (896, 'id_member_anonymous'),
 (897, 'id_member_anonymous'),
 (898, 'id_member_anonymous'),
 (900, 'id_member_anonymous'),
 (901, 'id_member_anonymous'),
 (903, 'id_member_anonymous'),
 (904, 'id_member_anonymous'),
 (908, 'id_member_anonymous'),
 (909, 'id_member_anonymous'),
 (910, 'id_member_anonymous'),
 (911, 'id_member_anonymous'),
 (912, 'id_member_anonymous'),
 (913, 'id_member_anonymous'),
 (917, 'id_member_anonymous'),
 (918, 'id_member_anonymous'),
 (919, 'id_member_anonymous'),
 (921, 'id_member_anonymous'),
 (922, 'id_member_anonymous'),
 (923, 'id_member_anonymous'),
 (924, 'id_member_anonymous'),
 (925, 'id_member_anonymous'),
 (929, 'id_member_anonymous'),
 (933, 'id_member_anonymous'),
 (934, 'id_member_anonymous'),
 (935, 'id_member_anonymous'),
 (936, 'id_member_anonymous'),
 (937, 'id_member_anonymous'),
 (941, 'id_member_anonymous'),
 (943, 'id_member_anonymous'),
 (944, 'id_member_anonymous'),
 (947, 'id_member_anonymous'),
 (948, 'id_member_anonymous'),
 (949, 'id_member_anonymous'),
 (950, 'id_member_anonymous'),
 (952, 'id_member_anonymous'),
 (954, 'id_member_anonymous'),
 (956, 'id_member_anonymous'),
 (957, 'id_member_anonymous'),
 (958, 'id_member_anonymous'),
 (960, 'id_member_anonymous'),
 (961, 'id_member_anonymous'),
 (962, 'id_member_anonymous'),
 (964, 'id_member_anonymous'),
 (965, 'id_member_anonymous'),
 (966, 'id_member_anonymous'),
 (967, 'id_member_anonymous'),
 (971, 'id_member_anonymous'),
 (972, 'id_member_anonymous'),
 (976, 'id_member_anonymous'),
 (978, 'id_member_anonymous'),
 (979, 'id_member_anonymous'),
 (980, 'id_member_anonymous'),
 (981, 'id_member_anonymous'),
 (982, 'id_member_anonymous'),
 (986, 'id_member_anonymous'),
 (988, 'id_member_anonymous'),
 (992, 'id_member_anonymous'),
 (993, 'id_member_anonymous'),
 (995, 'id_member_anonymous'),
 (996, 'id_member_anonymous'),
 (998, 'id_member_anonymous'),
 (1001, 'id_member_anonymous'),
 (1002, 'id_member_anonymous'),
 (1004, 'id_member_anonymous'),
 (1005, 'id_member_anonymous'),
 (1006, 'id_member_anonymous'),
 (1010, 'id_member_anonymous'),
 (1011, 'id_member_anonymous'),
 (1012, 'id_member_anonymous'),
 (1013, 'id_member_anonymous'),
 (1014, 'id_member_anonymous'),
 (1015, 'id_member_anonymous'),
 (1016, 'id_member_anonymous'),
 (1019, 'id_member_anonymous'),
 (1020, 'id_member_anonymous'),
 (1022, 'id_member_anonymous'),
 (1025, 'id_member_anonymous'),
 (1026, 'id_member_anonymous'),
 (1027, 'id_member_anonymous'),
 (1028, 'id_member_anonymous'),
 (1029, 'id_member_anonymous'),
 (1030, 'id_member_anonymous'),
 (1031, 'id_member_anonymous'),
 (1032, 'id_member_anonymous'),
 (1033, 'id_member_anonymous'),
 (1034, 'id_member_anonymous'),
 (1035, 'id_member_anonymous'),
 (1036, 'id_member_anonymous'),
 (1038, 'id_member_anonymous'),
 (1039, 'id_member_anonymous'),
 (1040, 'id_member_anonymous'),
 (1041, 'id_member_anonymous'),
 (1042, 'id_member_anonymous'),
 (1043, 'id_member_anonymous'),
 (1045, 'id_member_anonymous'),
 (1046, 'id_member_anonymous'),
 (1049, 'id_member_anonymous'),
 (1051, 'id_member_anonymous'),
 (1052, 'id_member_anonymous'),
 (1053, 'id_member_anonymous'),
 (1054, 'id_member_anonymous'),
 (1056, 'id_member_anonymous'),
 (1057, 'id_member_anonymous'),
 (1058, 'id_member_anonymous'),
 (1059, 'id_member_anonymous'),
 (1060, 'id_member_anonymous'),

In [77]:
# Printa os primeiros 10 valores nulos do array
array_faltantes[:10]

[(1, 'id_member_anonymous'),
 (5, 'id_member_anonymous'),
 (11, 'id_member_anonymous'),
 (12, 'id_member_anonymous'),
 (14, 'id_member_anonymous'),
 (17, 'id_member_anonymous'),
 (21, 'id_member_anonymous'),
 (22, 'id_member_anonymous'),
 (24, 'id_member_anonymous'),
 (25, 'id_member_anonymous')]

In [78]:
# Printa os últimos 10 valores nulos do array
array_faltantes[-10:]

[(496768, 'media_md5'),
 (496769, 'media_md5'),
 (496770, 'media_md5'),
 (496771, 'media_md5'),
 (496772, 'media_md5'),
 (496773, 'media_md5'),
 (496774, 'media_md5'),
 (496775, 'media_md5'),
 (496776, 'media_md5'),
 (496779, 'media_md5')]

## c)  Contar quantas linhas possuem valores faltantes.

In [79]:
# Soma a quantidade de valores nulos por linha
quantidade_linhas_faltantes = df.isnull().any(axis=1).sum()
print(f"Quantidade de linhas com valores faltantes: {quantidade_linhas_faltantes}")

Quantidade de linhas com valores faltantes: 557561

## d)  Para cada coluna (feature), contar quantas linhas possuem valores faltantes.

In [80]:
# Soma a quantidade de valores nulos por coluna
quantidade_linhas_faltantes_colunas = df.isnull().sum()
print(f"Quantidade de linhas com valores faltantes por coluna: \n\n{quantidade_linhas_faltantes_colunas}")

Quantidade de linhas com valores faltantes por coluna:

date_message                   0
id_member_anonymous       323341
id_group_anonymous             0
media                     224981
media_type                224981
media_url                 400141
has_media                      0
has_media_url                  0
trava_zap                      0
text_content_anonymous    113385
dataset_info_id                0
date_system                    0
score_sentiment           113429
score_misinformation      390348
id_message                     0
message_type                   0
messenger                      0
media_name                528599
media_md5                 224981
dtype: int64

## e)  Identificar e listar as linhas repetidas (duplicadas).

In [81]:
# Identifica os valores duplicados e printa a quantidade de linhas duplicadas
linhas_duplicadas = df.duplicated()
print(f"Quantidade de linhas duplicadas: {linhas_duplicadas.sum()}")

Quantidade de linhas duplicadas: 0

## f)  Identificar e listar  as posições (células) contendo valores que não pertencem ao domínio (tipo de dados) esperado.

In [82]:
# Identifica os domínios das colunas
df.dtypes

date_message               object
id_member_anonymous        object
id_group_anonymous         object
media                      object
media_type                 object
media_url                  object
has_media                    bool
has_media_url                bool
trava_zap                    bool
text_content_anonymous     object
dataset_info_id             int64
date_system                object
score_sentiment           float64
score_misinformation      float64
id_message                  int64
message_type               object
messenger                  object
media_name                 object
media_md5                  object
dtype: object

### Código com multithread

In [83]:
# Inicializa o array de inconsistências.
array_inconsistencias = []

# Define a função de identificar as inconsistências.
def f(coluns):
    # Identifica o tipo da coluna.
    type_colun = type(df[coluns].dtype)
    # Instância um array interno para a utilização da multithread.
    array_inconsistencias = []
    # Loop para percorrer todas as linhas da coluna.
    for i in range(len(df)):
        # Verifica se o tipo do dado é diferente do tipo da coluna.
        if  isinstance(df.at[i, coluns], type_colun) :
            # Se o tipo do dados for diferente adicina ao array.
            array_inconsistencias.append((i, coluns))
    # Retorna o array interno.
    return array_inconsistencias

# Conta o número de cpus possíveis para thread.
num_processos = multiprocessing.cpu_count()

# Utilizando a biblioteca multiprocessing para executar o código em multiplas threads, onde é passado a quantidade de threads possíveis que pode abrir.
with multiprocessing.Pool(processes=num_processos) as pool:
    # Adiciona ao array global o resultado obtido em cada array analisado em cada thread.

    array_inconsistencias.append(pool.map(f, df.columns))

In [84]:
# Printa o array
array_inconsistencias

[[[], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], []]]

### Código com loop

In [85]:
# Inicializa o array de inconsistências.
array_inconsistencias = []

# Loop para percorrer todas as colunas do dataset.
for coluns in df.columns:
    # Identifica o tipo da coluna.
    type_colun = type(df[coluns].dtype)
    # Loop para percorrer todas as linhas da coluna.
    for i in range(len(df)):
        # Verifica se o tipo do dado é diferente do tipo da coluna.
        if isinstance(df.at[i, coluns], type_colun):
            # Se o tipo do dados for diferente adicina ao array.
            array_inconsistencias.append((i, coluns))

In [86]:
# Printa o array
array_inconsistencias

[]

## g)  Crie  uma  coluna  chamada  “caracteres”  contendo  a  quantidade  de  caracteres  da coluna “text”.

In [87]:
# Criando a coluna 'caracteres' que armazena a quantidade de caracteres da coluna 'text_countent_anonymous'
df['caracteres'] = df['text_content_anonymous'].apply(lambda x: len(x) if isinstance(x, str) else 0)
# Printa a coluna caracteres
df['caracteres']

0         110
1         141
2         350
3          40
4           0
         ...
557581    152
557582     28
557583     68
557584     68
557585     68
Name: caracteres, Length: 557586, dtype: int64

## h)  Crie uma coluna chamada “words” contendo a quantidade de palavras da coluna “text”.

In [88]:
# Criando a coluna 'words' que armazena a quantidade de palavras da coluna 'text_countent_anonymous'
df['words'] = df['text_content_anonymous'].apply(lambda x: len(x.split()) if isinstance(x, str) else 0)
# Printa a coluna words
df['words']

0         20
1         23
2         59
3          7
4          0
          ..
557581    12
557582     1
557583     6
557584     6
557585     6
Name: words, Length: 557586, dtype: int64

## i)  Crie uma coluna chamada “viral” contendo o valor 0 se o texto da mensagem (valor do campo “text”) não for encontrado em outras linhas e 1, caso contrário.

In [89]:
# Criando a coluna 'viral' que armazena 0 se o texto não se repete em outra linha na coluna 'text_countent_anonymous' e 1 caso contrário 
df['viral'] = df.duplicated(subset='text_content_anonymous',keep=False).astype(int)
# Printa a coluna viral
df['viral']

0         0
1         0
2         0
3         0
4         1
         ..
557581    1
557582    1
557583    1
557584    1
557585    1
Name: viral, Length: 557586, dtype: int64

## j)  Crie uma coluna chamada “sharings” contendo a quantidade de vezes que o texto armazenado no atributo “text” aparece no dataset.

In [90]:
# Criando a coluna 'sharings' que armazena a qunatidade de vezes que o texto armazenado na coluna 'text_countent_anonymous' 
# aparece na 'text_countent_anonymous' que possui texto que posa ser comparado
df['sharings'] = df['text_content_anonymous'].map(df['text_content_anonymous'].value_counts())
# Printa a coluna Sharing
df['sharings']

0         1.0
1         1.0
2         1.0
3         1.0
4         NaN
         ...
557581    2.0
557582    2.0
557583    4.0
557584    4.0
557585    4.0
Name: sharings, Length: 557586, dtype: float64

## k)  Crie uma coluna chamada “sentiment” contendo os valores: -1 para textos negativos, 0 para textos neutros e 1 para textos positivos.

### Analisando sentimento através da coluna score_sentiment

In [91]:
# Cria a função que atribui -1 para sentimentos negativos, 0 para sentimento neutros e 1 para sentimentos positivos
def sentimento(val):
    # Verifica se o valor não é nulo
    if pd.isna(val):
        # Se for nulo retorna 0
        return 0   
    # Verifica se o sentimento é negativo
    elif val < 0:
        # Se for negativo retorna -1
        return -1
    # Verifica se o sentimento é 0
    elif val == 0:
        # Se for retorna 0
        return 0
    # Caso nenhuma das opções anteriores seja atendida é porque o sentimento é positivo
    else:
        # Entrando no else é retornado 1 que é sentimento positivo
        return 1

# Criando a coluna 'sentiment' onde é feito a análise da coluna 'scorte_sentiment' que retorna o valor do sentimento, com valores entre -1 e 1
df['sentiment'] = df['score_sentiment'].map(lambda x: sentimento(x))
# Printa a coluna sentiment 
df['sentiment']

0         0
1         1
2        -1
3         0
4         0
         ..
557581    1
557582    0
557583    0
557584    0
557585    0
Name: sentiment, Length: 557586, dtype: int64

### Analisando sentimento através da biblioteca LeIA

In [92]:
# Importando a biblioteca LeIA que identifica o sentimento de textos em português
from LeIA import SentimentIntensityAnalyzer

# Instanciando a função de analise de sentimento em s
s = SentimentIntensityAnalyzer()

# Criando a coluna 'score_sentiment_leia' aplicando a função de analise de sentimento em todas as linhas da coluna 'text_content_anonymous'
df['score_sentiment_leia'] = df['text_content_anonymous'].apply(lambda x: s.polarity_scores(x)['compound'] if isinstance(x, str) else 0)
# Printa a coluna score_sentiment_leia
df['score_sentiment_leia']

0         0.0000
1         0.0644
2        -0.3551
3         0.0000
4         0.0000
           ...
557581    0.1027
557582    0.0000
557583    0.0000
557584    0.0000
557585    0.0000
Name: score_sentiment_leia, Length: 557586, dtype: float64

### Analisando sentimento através da biblioteca vader

In [93]:
# Importando a biblioteca vader que identifica o sentimento de textos em inglês
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer

# Instanciando a função de analise de sentimento em s
s = SentimentIntensityAnalyzer()

# Criando a coluna 'score_sentiment_vader' aplicando a função de analise de sentimento em todas as linhas da coluna 'text_content_anonymous'
df['score_sentiment_vader'] = df['text_content_anonymous'].apply(lambda x: s.polarity_scores(x)['compound'] if isinstance(x, str) else 0)
# Printa a coluna score_sentiment_vader
df['score_sentiment_vader']

0        -0.5267
1        -0.5267
2        -0.2960
3         0.0000
4         0.0000
           ...
557581   -0.2960
557582    0.0000
557583    0.0000
557584    0.0000
557585    0.0000
Name: score_sentiment_vader, Length: 557586, dtype: float64

### Diferença da analise de sentimento realizado com api para analise de sentimento de texto em português baseada na vader que é a LeIA feita a partir da coluna score_sentiment

In [94]:
# Criando a coluna 'sentiment' onde é feito a análise da coluna 'scorte_sentiment_leia' que retorna o valor do sentimento, com valores entre -1 e 1
df['sentiment_leia'] = df['score_sentiment_leia'].map(lambda x: sentimento(x))

# Verificando a diferença entre a coluna 'sentiment' e a coluna 'sentiment_leia'
diferencas = df['sentiment'] != df['sentiment_leia']

# Exibir os valores das colunas apenas nas linhas diferentes
valores_diferentes = df.loc[diferencas, ['sentiment', 'sentiment_leia']]

# Printa a diferença na analise se sentimento da coluna sentimento já existente no dataset e a gerada utilizando o LeIA 
print(valores_diferentes)

        sentiment  sentiment_leia
840             0               1
3983            0               1
5683            1               0
6701            0               1
9875           -1               0
...           ...             ...
557573          0               1
557574          0              -1
557575          0              -1
557579          0               1
557580          0              -1

[95 rows x 2 columns]

### Diferença da analise de sentimento realizado com api para analise de sentimento chamada vader feita a partir da coluna score_sentiment

In [95]:
# Criando a coluna 'sentiment' onde é feito a análise da coluna 'scorte_sentiment_vader' que retorna o valor do sentimento, com valores entre -1 e 1
df['sentiment_vader'] = df['score_sentiment_vader'].map(lambda x: sentimento(x))

# Verificando a diferença entre a coluna 'sentiment' e a coluna 'sentiment_vader'
diferencas = df['sentiment'] != df['sentiment_vader']

# Exibir os valores das colunas apenas nas linhas diferentes
valores_diferentes = df.loc[diferencas, ['sentiment', 'sentiment_vader']]

# Printa a diferença na analise se sentimento da coluna sentimento já existente no dataset e a gerada utilizando a vader 
print(valores_diferentes)

        sentiment  sentiment_vader
0               0               -1
1               1               -1
6               1               -1
11             -1                1
16              1               -1
...           ...              ...
557565         -1                0
557574          0               -1
557579          0               -1
557580          0               -1
557581          1               -1

[228453 rows x 2 columns]

### A diferença nas três colunas de analises de sentimento

In [96]:
# Verificando a diferença entre a coluna 'sentiment', 'sentiment_leia' e 'sentiment_vader' 
diferencas = ((df['sentiment'] != df['sentiment_vader'])| (df['sentiment'] != df['sentiment_leia']))

# Exibir os valores das colunas apenas nas linhas diferentes
valores_diferentes = df.loc[diferencas, ['sentiment', 'sentiment_vader', 'sentiment_leia',]]

# Printa a diferença na analise se sentimento da coluna sentimento já existente no dataset com a gerada utilizando a vader e com a gerada utilizando LeIA
print(valores_diferentes)

        sentiment  sentiment_vader  sentiment_leia
0               0               -1               0
1               1               -1               1
6               1               -1               1
11             -1                1              -1
16              1               -1               1
...           ...              ...             ...
557574          0               -1              -1
557575          0                0              -1
557579          0               -1               1
557580          0               -1              -1
557581          1               -1               1

[228493 rows x 3 columns]

## l)  Eliminar as linhas cujo valor da coluna “text” contenham “trava-zaps”.

In [97]:
# Importando a biblioteca de regex
import re

# Criando uma função que identifica trava-zaps
def verificar_trava_zap(texto):
    # 1. Verificar tamanho do texto, principal indicativo de um trava-zap
    if len(texto) > 10000:
        # 2. Caracteres invisíveis/suspeitos
        caracteres_invisiveis = ['\u200b', '\u200c', '\u200d', '\u2063', '\ufeff']
        if any(char in texto for char in caracteres_invisiveis):
            return True

        # 3. Repetição exagerada de emojis ou caracteres
        if re.search(r'(.)\1{30,}', texto):  # mesmo caractere repetido 30 vezes ou mais
            return True

        # 4. Mistura incomum de alfabetos (regex para identificar scripts diferentes)
        if re.search(r'[а-яА-Я]+.*[a-zA-Z]+|[a-zA-Z]+.*[а-яА-Я]+', texto):
            return True
    
    # Se não tiver nenhuma condição válida ele retorna false
    return False

In [98]:
# Cria a coluna 'trava_zap_analisado' utilizando a função verifica_trava_zap
df['trava_zap_analisado']= df['text_content_anonymous'].apply(lambda x:verificar_trava_zap(x) if isinstance(x, str) else False)
# Printa a coluna trava_zap_analisado
df['trava_zap_analisado']

0         False
1         False
2         False
3         False
4         False
          ...
557581    False
557582    False
557583    False
557584    False
557585    False
Name: trava_zap_analisado, Length: 557586, dtype: bool

In [99]:
# Soma a quantidade de elementos com True na coluna 'trava_zap_analisado'
print(df['trava_zap_analisado'].sum())

0

In [100]:
# Soma a quantidade de elementos com True na coluna 'trava_zap' já existente no dataset
print(df['trava_zap'].sum())

16

### Acabei de realizar dois tipos de análises de trava-zap, uma verificando se as mensagens se adequava a um estilo de mensagem trava-zap a partir de uma função criada por mim com base em padrões de trava-zap, como não foi encontrado nenhum que se adequasse retirei apenas os que já eram declarados na coluna 'trava_zap'

In [101]:
# Retira as linhas que possuem trava-zap
df = df[df['trava_zap'] == False]
# Printa o dataset resultante
df

,date_message,id_member_anonymous,id_group_anonymous,media,media_type,media_url,has_media,has_media_url,trava_zap,text_content_anonymous,...,caracteres,words,viral,sharings,sentiment,score_sentiment_leia,score_sentiment_vader,sentiment_leia,sentiment_vader,trava_zap_analisado
0,2022-10-05 06:25:04,1078cc958f0febe28f4d03207660715f,12283e08a2eb5789201e105b34489ee7,NaN,NaN,NaN,False,False,False,Então é Fato Renato o áudio que eu ouvi no wha...,...,110,20,0,1.0,0,0.0000,-0.5267,0,-1,False
1,2022-10-05 06:25:08,NaN,12283e08a2eb5789201e105b34489ee7,NaN,NaN,NaN,False,False,False,"Saiu no YouTube do presidente a 8 horas atrás,...",...,141,23,0,1.0,1,0.0644,-0.5267,1,-1,False
2,2022-10-05 06:26:28,92a2d8fd7144074f659d1d29dc3751da,9f2d7394334eb224c061c9740b5748fc,NaN,NaN,NaN,False,False,False,"É isso, nossa parte já foi quase toda feita. N...",...,350,59,0,1.0,-1,-0.3551,-0.2960,-1,-1,False
3,2022-10-05 06:27:28,d60aa38f62b4977426b70944af4aff72,c8f2de56550ed0bf85249608b7ead93d,94dca4cda503100ebfda7ce2bcc060eb.jpg,image/jpg,NaN,True,False,False,GENTE ACHEI ELES EM UMA SEITA MAÇONÁRICA,...,40,7,0,1.0,0,0.0000,0.0000,0,0,False
4,2022-10-05 06:27:44,cd6979b0b5265f08468fa1689b6300ce,e56ec342fc599ebb4ed89655eb6f03aa,5ad5c8bbe9da93a37fecf3e5aa5b0637.jpg,image/jpg,NaN,True,False,False,NaN,...,0,0,1,NaN,0,0.0000,0.0000,0,0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
557581,2022-11-11 12:06:15,333e9869f23dbd4682d1be382d9c1e59,e56ec342fc599ebb4ed89655eb6f03aa,25e43b6a58b848c43ad5b5f9e979822a.jpg,url,https://terrabrasilnoticias.com/2022/11/bndes-...,True,True,False,"BNDES tem lucro de R$ 9,6 bilhões no terceiro ...",...,152,12,1,2.0,1,0.1027,-0.2960,1,-1,False
557582,2022-11-11 12:09:08,NaN,5b10d7739171149be6d9961e3350c071,657949d03e4088f6b332e2686ccd3221.jpg,url,https://youtu.be/8g1Vz9_0xVk,True,True,False,https://youtu.be/8g1Vz9_0xVk,...,28,1,1,2.0,0,0.0000,0.0000,0,0,False
557583,2022-11-11 12:09:47,NaN,1590a03f43b5ba4b6147a1c5e1dd357b,a21848a61045380a6483866daed0ca0e.jpg,image/jpg,https://t.me/vemprasruas,True,True,False,"Empresários, demitam os petistas primeiro.\n\n...",...,68,6,1,4.0,0,0.0000,0.0000,0,0,False
557584,2022-11-11 12:09:46,NaN,5b10d7739171149be6d9961e3350c071,a21848a61045380a6483866daed0ca0e.jpg,image/jpg,https://t.me/vemprasruas,True,True,False,"Empresários, demitam os petistas primeiro.\n\n...",...,68,6,1,4.0,0,0.0000,0.0000,0,0,False
557585,2022-11-11 12:09:48,NaN,b11f2df64ac19aad47a50accf32052d6,a21848a61045380a6483866daed0ca0e.jpg,image/jpg,https://t.me/vemprasruas,True,True,False,"Empresários, demitam os petistas primeiro.\n\n...",...,68,6,1,4.0,0,0.0000,0.0000,0,0,False

## m) Identificar inconsistências entre os atributos (features).

In [102]:
# Verifica se has_media == True, mas media ou media_type está NaN ou vazio.
inconsistentes_1 = df[(df['has_media'] == True) & (df['media'].isna() | df['media_type'].isna())]
# Printa as inconsistencias
inconsistentes_1

Empty DataFrame
Columns: [date_message, id_member_anonymous, id_group_anonymous, media, media_type, media_url, has_media, has_media_url, trava_zap, text_content_anonymous, dataset_info_id, date_system, score_sentiment, score_misinformation, id_message, message_type, messenger, media_name, media_md5, caracteres, words, viral, sharings, sentiment, score_sentiment_leia, score_sentiment_vader, sentiment_leia, sentiment_vader, trava_zap_analisado]
Index: []

[0 rows x 29 columns]

In [103]:
# Verifica se has_media_url == True mas media_url está vazio ou NaN.
inconsistentes_2 = df[(df['has_media_url'] == True) & (df['media_url'].isna() | (df['media_url'] == ''))]
# Printa as inconsistencias
inconsistentes_2

Empty DataFrame
Columns: [date_message, id_member_anonymous, id_group_anonymous, media, media_type, media_url, has_media, has_media_url, trava_zap, text_content_anonymous, dataset_info_id, date_system, score_sentiment, score_misinformation, id_message, message_type, messenger, media_name, media_md5, caracteres, words, viral, sharings, sentiment, score_sentiment_leia, score_sentiment_vader, sentiment_leia, sentiment_vader, trava_zap_analisado]
Index: []

[0 rows x 29 columns]

### Essa inconsistência em expecífico deveria ser feita no início, já que aqui já foi retirado os trava-zap do dataset, porém irei analisar com a coluna gerada por mim a 'trava_zap_analisado'

In [104]:
# Verifica se trava_zap == True mas text_content_anonymous é vazio ou muito curto.
inconsistentes_3 = df[(df['trava_zap'] == True) & (df['text_content_anonymous'].isna() | (df['text_content_anonymous'].str.len() < 50))]
# Printa as inconsistencias
inconsistentes_3

Empty DataFrame
Columns: [date_message, id_member_anonymous, id_group_anonymous, media, media_type, media_url, has_media, has_media_url, trava_zap, text_content_anonymous, dataset_info_id, date_system, score_sentiment, score_misinformation, id_message, message_type, messenger, media_name, media_md5, caracteres, words, viral, sharings, sentiment, score_sentiment_leia, score_sentiment_vader, sentiment_leia, sentiment_vader, trava_zap_analisado]
Index: []

[0 rows x 29 columns]

In [105]:
# Verifica se trava_zap_analisado == True mas text_content_anonymous é vazio ou muito curto.
inconsistentes_3_1= df[(df['trava_zap_analisado'] == True) & (df['text_content_anonymous'].isna() | (df['text_content_anonymous'].str.len() < 50))]
# Printa as inconsistencias
inconsistentes_3_1

Empty DataFrame
Columns: [date_message, id_member_anonymous, id_group_anonymous, media, media_type, media_url, has_media, has_media_url, trava_zap, text_content_anonymous, dataset_info_id, date_system, score_sentiment, score_misinformation, id_message, message_type, messenger, media_name, media_md5, caracteres, words, viral, sharings, sentiment, score_sentiment_leia, score_sentiment_vader, sentiment_leia, sentiment_vader, trava_zap_analisado]
Index: []

[0 rows x 29 columns]

In [106]:
# Verifica se score_sentiment fora da faixa esperada.
inconsistentes_4 = df[(df['score_sentiment'] < -1) | (df['score_sentiment'] > 1)]
# Printa as inconsistencias
inconsistentes_4

Empty DataFrame
Columns: [date_message, id_member_anonymous, id_group_anonymous, media, media_type, media_url, has_media, has_media_url, trava_zap, text_content_anonymous, dataset_info_id, date_system, score_sentiment, score_misinformation, id_message, message_type, messenger, media_name, media_md5, caracteres, words, viral, sharings, sentiment, score_sentiment_leia, score_sentiment_vader, sentiment_leia, sentiment_vader, trava_zap_analisado]
Index: []

[0 rows x 29 columns]

In [107]:
# Verifica se score_misinformation negativo ou nulo com mensagem suspeita.
inconsistentes_5 = df[(df['trava_zap'] == True) & ((df['score_misinformation'].isna()) | (df['score_misinformation'] <= 0))]
# Printa as inconsistencias
inconsistentes_5

Empty DataFrame
Columns: [date_message, id_member_anonymous, id_group_anonymous, media, media_type, media_url, has_media, has_media_url, trava_zap, text_content_anonymous, dataset_info_id, date_system, score_sentiment, score_misinformation, id_message, message_type, messenger, media_name, media_md5, caracteres, words, viral, sharings, sentiment, score_sentiment_leia, score_sentiment_vader, sentiment_leia, sentiment_vader, trava_zap_analisado]
Index: []

[0 rows x 29 columns]

In [108]:
# Verifica se date_message depois de date_system
inconsistentes_6 = df[df['date_message'] > df['date_system']]
# Printa as inconsistencias
inconsistentes_6

Empty DataFrame
Columns: [date_message, id_member_anonymous, id_group_anonymous, media, media_type, media_url, has_media, has_media_url, trava_zap, text_content_anonymous, dataset_info_id, date_system, score_sentiment, score_misinformation, id_message, message_type, messenger, media_name, media_md5, caracteres, words, viral, sharings, sentiment, score_sentiment_leia, score_sentiment_vader, sentiment_leia, sentiment_vader, trava_zap_analisado]
Index: []

[0 rows x 29 columns]

In [109]:
# Verifica se message_type ou messenger nulos com outros dados válidos
inconsistentes_7 = df[(df['message_type'].isna()) & ((~df['media'].isna()) | (~df['text_content_anonymous'].isna()))]
# Printa as inconsistencias
inconsistentes_7

Empty DataFrame
Columns: [date_message, id_member_anonymous, id_group_anonymous, media, media_type, media_url, has_media, has_media_url, trava_zap, text_content_anonymous, dataset_info_id, date_system, score_sentiment, score_misinformation, id_message, message_type, messenger, media_name, media_md5, caracteres, words, viral, sharings, sentiment, score_sentiment_leia, score_sentiment_vader, sentiment_leia, sentiment_vader, trava_zap_analisado]
Index: []

[0 rows x 29 columns]

In [ ]:
# Verificar se viral é 1 apenas quando há duplicatas em text_content_anonymous
inconsistentes_8 = df[(df['viral'] == 1) & (~df.duplicated(subset=['text_content_anonymous'], keep=False))]
# Printa as inconsistencias
inconsistentes_8

Empty DataFrame
Columns: [date_message, id_member_anonymous, id_group_anonymous, media, media_type, media_url, has_media, has_media_url, trava_zap, text_content_anonymous, dataset_info_id, date_system, score_sentiment, score_misinformation, id_message, message_type, messenger, media_name, media_md5, caracteres, words, viral, sharings, sentiment, score_sentiment_leia, score_sentiment_vader, sentiment_leia, sentiment_vader, trava_zap_analisado]
Index: []

[0 rows x 29 columns]